language: java
install:
- export main_repo_branch=$TRAVIS_BRANCH
- if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" ]]; then main_repo_branch=development ; fi
- git clone https://github.com/openworm/org.geppetto.model.git -b $main_repo_branch
- cd org.geppetto.model
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.core.git -b $main_repo_branch
- cd org.geppetto.core
- mvn install
- cd ..
env:
  global:
    secure: pIH0KE7Ps4z3I8WxfQM27cbncwWq7i5hyMea/w8hanStUulnsw0NDCVC/7molPtdM9l7sDkyJFSGRRLIt+Dt3uTFfVbJCxVXyF1G22yQhqp3y5BBMqFbz/9y9DRJly/DJWxtk0QvzG7kxtouq04UTU9TDVInut4HO9+LHvFkDUI=
